### ISSUE TITLE
ItemStack component override model-data even if it's being redefined by another component after

### ISSUE THREAD

**Issue by AmeliaCute** [MignonPetitXelow/Momento#9]
```yml
test_block:
    ItemStack:
      name: "gay sex"
      model-data: 123
    BlockItem:
      model-data: 123
      identifier: "test_block"
```
